### ISSUE TITLE
Not able to run demo.

### ISSUE THREAD

**Issue by rnb007** [QianliM/CAPE#5]
None

**Comment by rnb007** [comment]
Some changes in Load data file  i.e allow_pickle=True for numpy version 1.19

**Comment by pmy124** [comment]
I met the same question, could you please tell me how to solve this problem?

**Comment by qianlim** [comment]
> I met the same question, could you please tell me how to solve this problem?

Hi, can you be more specific? What errors did you encounter?

**Comment by omarmohamed101** [comment]
@qianlim i managed to run the demo but the generated examples are similar to each other and i cant see the clothes clearly. what is the problem? is that normal?
![Screenshot from 2021-08-25 19-06-07](https://user-images.githubusercontent.com/42470033/130834484-cf1c0d64-3f27-44f7-a12e-caf9d0dc0f7a.png)

**Comment by qianlim** [comment]
> @qianlim i managed to run the demo but the generated examples are similar to each other and i cant see the clothes clearly. what is the problem? is that normal?
> ![Screenshot from 2021-08-25 19-06-07](https://user-images.githubusercontent.com/42470033/130834484-cf1c0d64-3f27-44f7-a12e-caf9d0dc0f7a.png)

Hi, yes this is the typical output from the CAPE model. For the example you provided, the upper body are both tight fitted T-shirts but there's a clear difference in the pants (long vs short). In general, since the clothing and the body are represented together as a single mesh, the clothing edges can be not very sharp.
